export const OPENSPEC_SUPPORTED_TOOLS = [
  'amazon-q',
  'antigravity',
  'auggie',
  'bob',
  'claude',
  'cline',
  'codex',
  'forgecode',
  'codebuddy',
  'continue',
  'costrict',
  'crush',
  'cursor',
  'factory',
  'gemini',
  'github-copilot',
  'iflow',
  'junie',
  'kilocode',
  'kimi',
  'kiro',
  'opencode',
  'pi',
  'qoder',
  'lingma',
  'qwen',
  'roocode',
  'trae',
  'windsurf',
] as const

export type OpenSpecTool = (typeof OPENSPEC_SUPPORTED_TOOLS)[number]
